DROP VIEW IF EXISTS v02007_salesdetail;
CREATE VIEW v02007_salesdetail
AS
    SELECT 
	a.Code,
	a.Status MStatus,
	a.SourceType,
	a.Source,
	a.Type,
	a.ReceiptDate,
	a.OrderTime,
	a.CustomerUuid,
	a.CustomerName,
	a.CustomerType,
	a.CustomerCategory,
	a.CustomerCutOffTime,
	a.SalerName,
	a.ReceiverName,
	a.ReceiverContacterPhone,
	a.ReceiverAddress,
	a.TotalOrderAmount,
	a.TotalPreferenceAmount,
	a.TotalTurnoverAmount,
	a.TotalReceivableAmount,
	a.TotalOutputAmount,
	a.TakeAccountTotalAmount,
	a.Surcharges,
	a.SettlementStatus,
	a.SettlementMethod,
	a.Theme,
	a.Remark MRemark,
	a.DisRequire,
	a.Uuid,
	a.CrtUuid,
	a.CrtName,
	a.CrtTime,
	a.Version,
	a.ReceiverContacterName,
	a.BcCode,
	a.TUuid,
	a.ReceiverId,
	a.MclCode,
	a.IsAbnormal,
	a.OperaterName,
	a.OperaterUuid,
	a.SalerUuid,
	a.Orderer,
	a.ShipmentStatus,
	a.IsSelfPickUp,
	b.*
    FROM joinfsc_sales.sales a
    JOIN joinfsc_sales.salesdetail b 
    ON a.Id = b.Mid;